### ISSUE TITLE
can't get it working in Laravel 5.6

### ISSUE THREAD

**Issue by leabdalla** [malhal/Laravel-Geographical#9]
I've just followed all readme steps but when I try to run migrations, it returns:

    PHP Fatal error:  Trait 'Malhal\Geographical' not found in /var/www/app/Place.php on line 13

       Symfony\Component\Debug\Exception\FatalErrorException  : Trait 'Malhal\Geographical' not found

      at /var/www/app/Place.php:13
         9|
        10| class Place extends Model
        11| {
        12|     use SoftDeletes;
      > 13|     use Geographical;
        14|
        15|     protected static $kilometers = true;
        16|     const LATITUDE  = 'pin_lat';

I tried many different ways to load the trait in my model:

    use Malhal\Geographical;
    use Geographical;
    use \Malhal\Geographical;
    ... etc

Am I doing something wrong?

**Comment by Grayda** [comment]
@leabdalla: Based on your other issue that you started after this one, you got it working.

What did you end up doing? Because I've tried the same things as you, including dumping autoload, removing and re-requiring the library, making sure it's auto-loaded, but I still get told the trait isn't found.

**Comment by leabdalla** [comment]
@Grayda I've just copied the entire `Geographical.php` from this repository and pasted it as `app/Traits/Geographical.php`. Don't need any changes.
Then you can use it normally, for example:

    <?php namespace App;
    use Illuminate\Database\Eloquent\Model;
    use App\Traits\Geographical;
    
    class Place extends Model
    {
        use Geographical;
        ...

**Comment by Grayda** [comment]
> I've just copied the entire `Geographical.php` from this repository and pasted it as `app/Traits/Geographical.php`. Don't need any changes.

I'll give that a shot, but I might poke around some more and see what's going on. I'm new to traits (having never needed them before), so this'll be a good learning experience for me. Plus if I get it working, I'll submit a PR so others won't need to copy files around to use such a useful class.

**Comment by Grayda** [comment]
Okay, so I got it to work, and I feel kind of silly because my fried brain completely forgot how namespacing works, even though I've been using it for the last year and a half:

You have to use it like this:

`use Malhal\Geographical\Geographical;`

Then you can `use Geographical` in the model. 

On the plus side, I now have a great understanding of how composer works.
